### ISSUE TITLE
Not working for 0.16?

### ISSUE THREAD

**Issue by adamlc** [killbill/killbill-invoice-test-plugin#1]
I think this plugin may need updating for 0.16 as I tried running it and got the following errors when an invoice was created:

```
2016-01-14 11:28:29,359 [bus_events-th] INFO  o.k.b.i.g.FixedAndRecurringInvoiceItemGenerator - Proposed Invoice items for invoiceId b324bd4d-cb29-4267-961d-0474294cc927 and accountId 6b389b1d-bae1-4259-a14a-fb7a5eb33894
DefaultBillingEvent{type=CREATE, effectiveDate=2016-01-14T11:28:27.000Z, planPhaseName=Enterprise_200-Monthly-evergreen, subscriptionId=33c0374c-8ddc-469f-a597-e9aa5722f645, totalOrdering=17}
    RECURRING{startDate=2016-01-14, endDate=2016-02-14, amount=1080.00, rate=1080.00, subscriptionId=33c0374c-8ddc-469f-a597-e9aa5722f645, linkedItemId=null}
2016-01-14 11:28:29,392 [Thread-6] WARN  o.k.b.k.0.19.0 - Failure in get_additional_invoice_items: wrong number of arguments calling `get_additional_invoice_items` (4 for 3)
/var/lib/killbill/bundles/plugins/ruby/killbill-invoice-test/0.1.0/ROOT/gems/gems/killbill-7.0.0/lib/killbill/gen/plugin-api/invoice_plugin_api.rb:69:in `getAdditionalInvoiceItems'
Killbill$$Plugin$$Api$$InvoicePluginApi_55303941.gen:13:in `getAdditionalInvoiceItems'
2016-01-14 11:28:29,398 [bus_events-th] ERROR o.k.q.d.CallableCallbackBase - Fatal NotificationQ dispatch error, data corruption...
com.google.common.eventbus.EventBusException: java.lang.reflect.InvocationTargetException
    at com.google.common.eventbus.EventBusThatThrowsException.dispatchWithException(EventBusThatThrowsException.java:108)
    at com.google.common.eventbus.EventBusThatThrowsException.dispatchQueuedEventsWithException(EventBusThatThrowsException.java:94)
    at com.google.common.eventbus.EventBusThatThrowsException.postWithException(EventBusThatThrowsException.java:82)
    at org.killbill.bus.DefaultPersistentBus.dispatchBusEventWithMetrics(DefaultPersistentBus.java:299)
    at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:40)
    at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:29)
    at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:102)
    at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:85)
    at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.EventBusThatThrowsException.dispatchWithException(EventBusThatThrowsException.java:106)
    ... 13 common frames omitted
Caused by: java.lang.reflect.UndeclaredThrowableException: null
    at com.sun.proxy.$Proxy158.getAdditionalInvoiceItems(Unknown Source)
    at org.killbill.billing.invoice.InvoicePluginDispatcher.getAdditionalInvoiceItems(InvoicePluginDispatcher.java:67)
    at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:349)
    at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:244)
    at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:213)
    at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:199)
    at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:174)
    at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:170)
    at org.killbill.billing.invoice.InvoiceListener.handleSubscriptionTransition(InvoiceListener.java:89)
    ... 19 common frames omitted
Caused by: org.killbill.billing.payment.plugin.api.PaymentPluginApiException: null
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:284)
    at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:97)
    at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:193)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:356)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:213)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
    at org.jruby.java.proxies.ConcreteJavaProxy$InitializeMethod.call(ConcreteJavaProxy.java:60)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:211)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
    at org.jruby.RubyClass.newInstance(RubyClass.java:863)
    at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
    at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:318)
    at org.jruby.java.proxies.ConcreteJavaProxy$NewMethod.call(ConcreteJavaProxy.java:162)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
    at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
    at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.ast.RescueBodyNode.interpret(RescueBodyNode.java:108)
    at org.jruby.ast.RescueNode.handleException(RescueNode.java:174)
    at org.jruby.ast.RescueNode.interpret(RescueNode.java:120)
    at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
    at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:169)
    at Killbill$$Plugin$$Api$$InvoicePluginApi_55303941.getAdditionalInvoiceItems(Killbill$$Plugin$$Api$$InvoicePluginApi_55303941.gen:13)
    at org.killbill.billing.osgi.bundles.jruby.JRubyInvoicePlugin$1.doCall(JRubyInvoicePlugin.java:51)
    at org.killbill.billing.osgi.bundles.jruby.JRubyInvoicePlugin$1.doCall(JRubyInvoicePlugin.java:48)
    at org.killbill.billing.osgi.bundles.jruby.JRubyPlugin.callWithRuntimeAndChecking(JRubyPlugin.java:315)
    at org.killbill.billing.osgi.bundles.jruby.JRubyInvoicePlugin.getAdditionalInvoiceItems(JRubyInvoicePlugin.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler$1.execute(ContextClassLoaderHelper.java:142)
    at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
    at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler.invoke(ContextClassLoaderHelper.java:139)
    ... 28 common frames omitted
```

**Comment by pierre** [comment]
```
2016-01-14 11:28:29,392 [Thread-6] WARN  o.k.b.k.0.19.0 - Failure in get_additional_invoice_items: wrong number of arguments calling `get_additional_invoice_items` (4 for 3)
```

Indeed: the API now accepts a `dryRun` parameter to distinguish real from dry-run invoices.

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-invoice-test-plugin/commit/ffa1d02be06d7e2c9bb2dbf915daae7afaff6ee4. 0.1.1 has been released.

Thanks!

**Comment by adamlc** [comment]
:smile:
